version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: stg_sellers
    columns:
      - name: seller_id
        tests:
          - unique
          - not_null

  - name: stg_order_reviews
    columns:
      - name: review_id
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - review_id
              - order_id

  - name: stg_category_translation
    columns:
      - name: product_category_name
        tests:
          - unique
          - not_null

  - name: stg_geolocation
    columns:
      - name: geolocation_zip_code_prefix
        tests:
          - not_null

  - name: stg_order_items
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - order_id
              - order_item_id

  - name: stg_order_payments
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - order_id
              - payment_sequential